channels:
  - tidair-packages
  - conda-forge
dependencies:
  - python=3.10
  - gcc_linux-64
  - gxx_linux-64
  - make
  - git
  - git-lfs
  - ipython
  - cmake
  - pyyaml
  - pyzmq
  - parse
  - click
  - numpy
  - pyqt
  - boost
  - bzip2
  - zeromq
  - sphinx
  - sphinx_rtd_theme
  - breathe
  - pyserial
  - sqlalchemy
  - pydm
  - matplotlib
  - pytest
  - pytest-cov
