channels:
  - tidair-packages
  - conda-forge
dependencies:
  - python>=3.8
  - clang_osx-64
  - clangxx_osx-64
  - make
  - git
  - git-lfs
  - ipython
  - cmake
  - pyyaml
  - pyzmq
  - parse
  - click
  - numpy
  - pyqt
  - boost
  - bzip2
  - zeromq
  - sqlalchemy
  - pydm
  - pyserial
  - matplotlib
  - pytest
  - pytest-cov
