channels:
  - defaults
  - tidair-packages
  - conda-forge
dependencies:
  - python
  - gcc_linux-64
  - gxx_linux-64
  - make
  - git
  - git-lfs
  - ipython
  - cmake
  - pyyaml
  - jsonpickle
  - pyzmq
  - parse
  - click
  - numpy
  - pyqt
  - pyepics
  - boost
  - bzip2
  - zeromq
  - epics-base
  - pcas
  - sphinx
  - sphinx_rtd_theme
  - breathe
  - p4p
  - sqlalchemy
  - pydm
