channels:
  - defaults
  - tidair-packages
  - conda-forge
dependencies:
  - python
  - clang_osx-64
  - clangxx_osx-64
  - make
  - git
  - git-lfs
  - ipython
  - cmake
  - pyyaml
  - jsonpickle
  - pyzmq
  - parse
  - click
  - numpy
  - pyqt
  - boost
  - bzip2
  - zeromq
  - sqlalchemy
