channels:
  - defaults
  - conda-forge
  - paulscherrerinstitute
dependencies:
  - python=3.6
  - clang_osx-64
  - clangxx_osx-64
  - git
  - git-lfs
  - ipython
  - make
  - cmake
  - pyyaml
  - pyzmq
  - parse
  - click
  - pyro4
  - numpy
  - pyqt
  - pyepics
  - boost
  - bzip2
  - epics-base=3.14.12.8
