package:
  name: rogue-epics3
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}

source:
   path: ..

build:
   number: {{ environ.get('GIT_DESCRIBE_NUMBER',0) }}

requirements:
   build:
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
     - git
     - cmake
     - make
   host:
     - python>=3.7
     - boost
     - bzip2
     - zeromq
     - numpy
     - epics-base
     - pcas
   run:
     - python
     - boost
     - bzip2
     - zeromq
     - numpy
     - ipython
     - p4p
     - pyyaml
     - jsonpickle
     - pyzmq
     - parse
     - click
     - sqlalchemy
     - pydm>=1.18.0
     - pyserial
     - matplotlib
     - epics-base
     - pcas

about:
   home: https://github.com/slaclab/rogue
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: SLAC Python Based Hardware Abstraction And Data Acquisition System

