package:
  name: rogue
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}

source:
   path: ..

build:
   number: {{ environ.get('GIT_DESCRIBE_NUMBER',0) }}

requirements:
   build:
     - python
     - boost
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
     - git
     - cmake
     - make
     - bzip2
     - zeromq
     - numpy
   host:
     - python
     - boost
     - bzip2
     - zeromq
     - numpy
   run:
     - python
     - boost
     - bzip2
     - zeromq
     - numpy
     - ipython
     - p4p
     - pyyaml
     - jsonpickle
     - pyzmq
     - parse
     - click
     - pyqt
     - sqlalchemy
     - pydm
     - pyserial
     - matplotlib

about:
   home: https://github.com/slaclab/rogue
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: SLAC Python Based Hardware Abstraction And Data Acquisition System

