package:
  name: rogue
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
   number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
   build:
     - python
     - boost=1.69
     - boost-cpp=1.69
     - gcc_linux-64   [linux]
     - gxx_linux-64   [linux]
     - clang_osx-64   [osx]
     - clangxx_osx-64 [osx]
     - git
     - cmake
     - make
     - bzip2
     - zeromq
     - epics-base [linux]
     - pcas       [linux]
     - numpy

   run:
     - python
     - boost=1.69
     - boost-cpp=1.69
     - gcc_linux-64   [linux]
     - gxx_linux-64   [linux]
     - clang_osx-64   [osx]
     - clangxx_osx-64 [osx]
     - cmake
     - make
     - bzip2
     - zeromq
     - epics-base [linux]
     - pcas       [linux]
     - numpy
     - ipython
     - p4p        [linux]
     - pyyaml
     - jsonpickle
     - pyzmq
     - parse
     - click
     - pyqt
     - pyepics    [linux]
     - sqlalchemy
     - pydm
     - pyserial

about:
   home: https://github.com/slaclab/rogue
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: SLAC Python Based Hardware Abstraction And Data Acquisition System

