package: 
  name: rogue
  version: {{ data.get{'version'}}}

source:
   path: ..

requirements:

   build:
     - gcc_linux-64
     - gxx_linux-64
     - python=3.6
     - boost
     - cmake
     - bzip2
     - epics-base=3.14.12.8

   run:
     - gcc_linux-64
     - gxx_linux-64
     - python=3.6
     - pyyaml
     - pyzmq
     - parse
     - click
     - pyro4
     - numpy
     - pyqt
     - boost
     - cmake
     - bzip2
     - matplotlib
     - epics-base=3.14.12.8

about:
   home: https://github.com/slaclab/rogue
   license: SLAC Open License

