package: 
  name: rogue
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
   number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
   build:
     - python=3.6
     - gcc_linux-64   [not osx]
     - gxx_linux-64   [not osx]
     - clang_osx-64   [osx]
     - clangxx_osx-64 [osx]
     - boost
     - cmake
     - make
     - bzip2
     - epics-base=3.14.12.8
     - git

   run:
     - python=3.6
     - gcc_linux-64   [not osx]
     - gxx_linux-64   [not osx]
     - clang_osx-64   [osx]
     - clangxx_osx-64 [osx]
     - git
     - git-lfs
     - ipython
     - boost
     - bzip2
     - epics-base=3.14.12.8
     - pyyaml
     - pyzmq
     - parse
     - click
     - pyro4
     - numpy
     - pyqt
     - pyepics
     - matplotlib

about:
   home: https://github.com/slaclab/rogue
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: SLAC Python Based Hardware Abstraction And Data Acquisition System

