package:
  name: rogue
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}

source:
   path: ..

build:
   number: {{ environ.get('GIT_DESCRIBE_NUMBER',0) }}

requirements:
   build:
     - python
     - boost
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
     - git
     - cmake
     - make
     - bzip2
     - zeromq
     - epics-base [linux]
     - pcas       [linux]
     - numpy
   host:
     - python
     - boost
     - bzip2
     - zeromq
     - epics-base [linux]
     - pcas       [linux]
     - libarchive [osx]
     - numpy
   run:
     - python
     - {{ pin_compatible('boost', min_pin='x.x', max_pin='x.x')}}
     - boost
     - bzip2
     - zeromq
     - epics-base [linux]
     - pcas       [linux]
     - numpy
     - ipython
     - p4p        [linux]
     - pyyaml
     - jsonpickle
     - pyzmq
     - parse
     - click
     - pyqt
     - pyepics    [linux]
     - sqlalchemy
     - pydm
     - pyserial

about:
   home: https://github.com/slaclab/rogue
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: SLAC Python Based Hardware Abstraction And Data Acquisition System

