package: 
  name: rogue
  version: {{ GIT_BUILD_STR }}

source:
   path: ..

requirements:
   build:
     - python=3.6
     - gcc_linux-64
     - gxx_linux-64
     - setuptools
     - boost
     - cmake
     - make
     - bzip2
     - epics-base=3.14.12.8
     - git

   run:
     - python=3.6
     - gcc_linux-64
     - gxx_linux-64
     - pyyaml
     - pyzmq
     - parse
     - click
     - pyro4
     - numpy
     - pyqt
     - boost
     - bzip2
     - matplotlib
     - epics-base=3.14.12.8

about:
   home: https://github.com/slaclab/rogue
   license: SLAC Open License

