package: 
  name: rogue
  version: v2.12.1

source:
   path: ..

requirements:
   build:
     - gcc_linux-64
     - gxx_linux-64
     - python
     - setuptools
     - boost
     - cmake
     - bzip2
     - epics-base=3.14.12.8
     - git

   run:
     - gcc_linux-64
     - gxx_linux-64
     - python
     - pyyaml
     - pyzmq
     - parse
     - click
     - pyro4
     - numpy
     - pyqt
     - boost
     - bzip2
     - matplotlib
     - epics-base=3.14.12.8

about:
   home: https://github.com/slaclab/rogue
   license: SLAC Open License

