name: Testing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2

      - name: Setup Environment
        run: |
         MAKEFLAGS="-j 2"
         EPICS_DIR=${GITHUB_WORKSPACE}/packages/epics/base-7.0.3
         EPICS_PCAS_DIR=${GITHUB_WORKSPACE}/packages/pcas/pcas-4.13.2
         MINICONDA_DIR=${GITHUB_WORKSPACE}/packages/miniconda
         echo "MAKEFLAGS=$MAKEFLAGS" >> $GITHUB_ENV
         echo "EPICS_DIR=$EPICS_DIR" >> $GITHUB_ENV
         echo "EPICS_PCAS_DIR=$EPICS_PCAS_DIR" >> $GITHUB_ENV
         echo "MINICONDA_DIR=$MINICONDA_DIR" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install setuptools
          pip3 install -r pip_requirements.txt

      - name: Install EPICS Base
        run: |
          echo "DIR = ${EPICS_DIR}"
          mkdir -p ${EPICS_DIR}
          cd ${EPICS_DIR}
          pwd
          wget -O base-7.0.3.tar.gz  https://github.com/epics-base/epics-base/archive/R7.0.3.tar.gz
          tar xzf base-7.0.3.tar.gz --strip 1
          make clean && make && make install

#LD_LIBRARY_PATH=/usr/lib:${EPICS_DIR}/lib/linux-x86_64:${EPICS_PCAS_DIR}/lib/linux-x86_64
