name: Testing
on: [push]

env:
  APP_NAME: My App
  MAKEFLAGS: "-j 2"
  PACKAGE_DIR: /packages
  EPICS_DIR: $PACKAGE_DIR/epics/base-7.0.3
  EPICS_PCAS_DIR: $PACKAGE_DIR/pcas/pcas-4.13.2
  LD_LIBRARY_PATH: /usr/lib:$EPICS_DIR/lib/linux-x86_64:$EPICS_PCAS_DIR/lib/linux-x86_64
  MINICONDA_DIR: $PACKAGE_DIR/miniconda
  DOCKER_ORG_NAME: tidair
  GITHUB_REPO: slaclab/rogue

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install setuptools
          pip3 install -r pip_requirements.txt

      - name: Install EPICS Base
        run: |
          mkdir -p $EPICS_DIR
          pwd
          cd $EPICS_DIR
          wget -O base-7.0.3.tar.gz  https://github.com/epics-base/epics-base/archive/R7.0.3.tar.gz
          tar xzf base-7.0.3.tar.gz --strip 1
          make clean && make && make install

